/* Generated By:JJTree: Do not edit this line. ASTArg.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package tree;

import parser.Parser;

public
class ASTArg extends SimpleNode {
  public ASTArg(int id) {
    super(id);
  }

  public ASTArg(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=65e3258530bc77788234457cf14dfd54 (do not edit this line) */
