/* Generated By:JJTree: Do not edit this line. ASTArgs.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package tree;

import parser.Parser;

public
class ASTArgs extends SimpleNode {
  public ASTArgs(int id) {
    super(id);
  }

  public ASTArgs(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=148bed802f3f3074991d57b1f0acdee4 (do not edit this line) */
