/* Generated By:JJTree: Do not edit this line. ASTAndNode.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package tree;

import parser.Parser;

public
class ASTAndNode extends SimpleNode {
  public ASTAndNode(int id) {
    super(id);
  }

  public ASTAndNode(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=df8920478d2c4e1c794b04ad7c7bc1b0 (do not edit this line) */
