/* Generated By:JJTree: Do not edit this line. ASTClassDecl.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package tree;

import parser.Parser;

public
class ASTClassDecl extends SimpleNode {

  private String name;

  public ASTClassDecl(int id) {
    super(id);
  }

  public ASTClassDecl(Parser p, int id) {
    super(p, id);
  }

  public void setName(String name) {
    this.name = name;
  }

  @Override
  public String toString() {
    return super.toString() + ": " + name;
  }
}
/* JavaCC - OriginalChecksum=35127634abb0df2fef04d026cabebba5 (do not edit this line) */
