/* Generated By:JJTree: Do not edit this line. ASTFalse.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package tree;

import parser.Parser;

public
class ASTFalse extends SimpleNode {
  public ASTFalse(int id) {
    super(id);
  }

  public ASTFalse(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f34ff1c325357000caa29eb347ea2993 (do not edit this line) */
