/* Generated By:JJTree: Do not edit this line. ASTFunctionCall.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package tree;

import parser.Parser;

public
class ASTFunctionCall extends SimpleNode {
  public ASTFunctionCall(int id) {
    super(id);
  }

  public ASTFunctionCall(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a60418388f25f3050be274a4e7561562 (do not edit this line) */
