/* Generated By:JJTree: Do not edit this line. ASTIdentifier.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package tree;

import parser.Parser;

public
class ASTIdentifier extends SimpleNode {

  private String name;

  public ASTIdentifier(int id) {
    super(id);
  }

  public ASTIdentifier(Parser p, int id) {
    super(p, id);
  }

  public void setName(String name) {
    this.name = name;
  }
  public String  getName() {
    return name;
  }

  @Override
  public String toString() {
    return super.toString() + ": " + name;
  }

}
/* JavaCC - OriginalChecksum=8f911c8e9c216133742c763c3f50505c (do not edit this line) */
