/* Generated By:JJTree: Do not edit this line. ASTInheritance.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package tree;

import parser.Parser;

public
class ASTInheritance extends SimpleNode {
  public ASTInheritance(int id) {
    super(id);
  }

  public ASTInheritance(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7c06ea42235372d3e81def0d9175b32e (do not edit this line) */
