/* Generated By:JJTree: Do not edit this line. ASTMulNode.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package tree;

import parser.Parser;

public
class ASTMulNode extends SimpleNode {
  public ASTMulNode(int id) {
    super(id);
  }

  public ASTMulNode(Parser p, int id) {
    super(p, id);
  }

  private String name;

  public void setName(String name) {
    this.name = name;
  }

  @Override
  public String toString() {
    return super.toString() + ": " + name;
  }

}
/* JavaCC - OriginalChecksum=ce7404641d4c26934ee0cfafcb810d84 (do not edit this line) */
