/* Generated By:JJTree: Do not edit this line. ASTMainClass.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package tree;

import parser.Parser;

public
class ASTMainClass extends SimpleNode {

  private String name;

  public ASTMainClass(int id) {
    super(id);
  }

  public ASTMainClass(Parser p, int id) {
    super(p, id);
  }

  public void setName(String name) {
    this.name = name;
  }

  @Override
  public String toString() {
    return super.toString() + ": " + name;
  }
}
/* JavaCC - OriginalChecksum=5c5b426c5212967c0001abb186e2254e (do not edit this line) */
