/* Generated By:JJTree: Do not edit this line. ASTMethodDecls.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package tree;

import parser.Parser;

public
class ASTMethodDecls extends SimpleNode {
  public ASTMethodDecls(int id) {
    super(id);
  }

  public ASTMethodDecls(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=73ed196441a2ec0ac77e6ee2fe73ba5e (do not edit this line) */
