/* Generated By:JJTree: Do not edit this line. ASTMethodDecl.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package tree;

import parser.Parser;

public
class ASTMethodDecl extends SimpleNode {
  public ASTMethodDecl(int id) {
    super(id);
  }

  public ASTMethodDecl(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e0b227f18c631666f62be6053cf52f07 (do not edit this line) */
