/* Generated By:JJTree: Do not edit this line. ASTMethodDecl.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package tree;
import parser.Parser;
public
class ASTMethodDecl extends SimpleNode {
  public ASTMethodDecl(int id) {
    super(id);
  }

  public ASTMethodDecl(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1c8d918c986ec88d2ef56d5be132df09 (do not edit this line) */
