/* Generated By:JJTree: Do not edit this line. ASTPrint.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package tree;

import parser.Parser;

public
class ASTPrint extends SimpleNode {
  public ASTPrint(int id) {
    super(id);
  }

  public ASTPrint(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2257b114b43145ec92db1efd255d81c6 (do not edit this line) */
