/* Generated By:JJTree: Do not edit this line. ASTRetrun.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package tree;

import parser.Parser;

public
class ASTRetrun extends SimpleNode {
  public ASTRetrun(int id) {
    super(id);
  }

  public ASTRetrun(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=be974fa1605d1708c41a04407f07ed86 (do not edit this line) */
