/* Generated By:JJTree: Do not edit this line. ASTRelNode.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package tree;

import parser.Parser;

public
class ASTRelNode extends SimpleNode {



  public ASTRelNode(int id) {
    super(id);
  }

  public ASTRelNode(Parser p, int id) {
    super(p, id);
  }

  private String name;

  public void setName(String name) {
    this.name = name;
  }

  @Override
  public String toString() {
    return super.toString() + ": " + name;
  }
}
/* JavaCC - OriginalChecksum=e2a76e7b2f370a94e9e03db946cba636 (do not edit this line) */
