/* Generated By:JJTree: Do not edit this line. ASTTypeArray.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package tree;

import parser.Parser;

public
class ASTTypeArray extends SimpleNode {
  public ASTTypeArray(int id) {
    super(id);
  }

  public ASTTypeArray(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bf540a8ca2acfdc68db13eeac80362b8 (do not edit this line) */
