/* Generated By:JJTree: Do not edit this line. ASTTrue.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package tree;

import parser.Parser;

public
class ASTTrue extends SimpleNode {
  public ASTTrue(int id) {
    super(id);
  }

  public ASTTrue(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=31904bb5127534711676674ebd410127 (do not edit this line) */
