/* Generated By:JJTree: Do not edit this line. ASTThis.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package tree;

import parser.Parser;

public
class ASTThis extends SimpleNode {
  public ASTThis(int id) {
    super(id);
  }

  public ASTThis(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1a66f885964864ae75dc46067ad28777 (do not edit this line) */
