/* Generated By:JJTree: Do not edit this line. ASTVarDecls.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package tree;
import parser.Parser;
public
class ASTVarDecls extends SimpleNode {
  public ASTVarDecls(int id) {
    super(id);
  }

  public ASTVarDecls(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6f278ff4eeea5f75ba5844ad5a0b9e60 (do not edit this line) */
