/* Generated By:JJTree: Do not edit this line. ASTVarDecl.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package tree;

import parser.Parser;

public
class ASTVarDecl extends SimpleNode {

  public ASTVarDecl(int id) {
    super(id);
  }

  public ASTVarDecl(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d187ab5b65acb1798d8b490eeb6d34da (do not edit this line) */
