/* Generated By:JJTree: Do not edit this line. ASTVecAccess.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package tree;

import parser.Parser;

public
class ASTVecAccess extends SimpleNode {
  public ASTVecAccess(int id) {
    super(id);
  }

  public ASTVecAccess(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8099f90f5c68cc7b4e8b7ef215efaef3 (do not edit this line) */
