/* Generated By:JJTree: Do not edit this line. ASTVarDecls.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package tree;

import parser.Parser;

public
class ASTVarDecls extends SimpleNode {
  public ASTVarDecls(int id) {
    super(id);
  }

  public ASTVarDecls(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8048cd026ba15c3bbdd2706819d55324 (do not edit this line) */
