/* Generated By:JJTree: Do not edit this line. ASTWhile.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package tree;

import parser.Parser;

public
class ASTWhile extends SimpleNode {
  public ASTWhile(int id) {
    super(id);
  }

  public ASTWhile(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2f75fd6152a760a09e179118266a724b (do not edit this line) */
