/* Generated By:JavaCC: Do not edit this line. ParserVisitor.java Version 7.0.11 */
package tree;

public interface ParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTIdentifier node, Object data);
  public Object visit(ASTMainClass node, Object data);
  public Object visit(ASTClassDecl node, Object data);
  public Object visit(ASTInheritance node, Object data);
  public Object visit(ASTVarDecls node, Object data);
  public Object visit(ASTMethodDecls node, Object data);
  public Object visit(ASTVarDecl node, Object data);
  public Object visit(ASTMethodDecl node, Object data);
  public Object visit(ASTArgs node, Object data);
  public Object visit(ASTRetrun node, Object data);
  public Object visit(ASTArg node, Object data);
  public Object visit(ASTType node, Object data);
  public Object visit(ASTBlock node, Object data);
  public Object visit(ASTIf node, Object data);
  public Object visit(ASTWhile node, Object data);
  public Object visit(ASTPrint node, Object data);
  public Object visit(ASTAssignment node, Object data);
  public Object visit(ASTOrNode node, Object data);
  public Object visit(ASTAndNode node, Object data);
  public Object visit(ASTRelNode node, Object data);
  public Object visit(ASTAddNode node, Object data);
  public Object visit(ASTMulNode node, Object data);
  public Object visit(ASTUnaryNode node, Object data);
  public Object visit(ASTVecAccess node, Object data);
  public Object visit(ASTFunctionCall node, Object data);
  public Object visit(ASTInteger node, Object data);
  public Object visit(ASTTrue node, Object data);
  public Object visit(ASTFalse node, Object data);
  public Object visit(ASTThis node, Object data);
}
/* JavaCC - OriginalChecksum=ea82724c8031ed8bb9525933e2d8e3d0 (do not edit this line) */
