/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 7.0.11 */
package tree;

public interface ParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTMAINCLASS = 1;
  public int JJTCLASSDECL = 2;
  public int JJTVARDECL = 3;
  public int JJTMETHODDECL = 4;
  public int JJTVOID = 5;
  public int JJTTYPE = 6;


  public String[] jjtNodeName = {
    "Program",
    "MainClass",
    "ClassDecl",
    "VarDecl",
    "MethodDecl",
    "void",
    "Type",
  };
}
/* JavaCC - OriginalChecksum=956cc5795506ed5724692f9a9df9f72a (do not edit this line) */
