/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 7.0.11 */
package tree;

public interface ParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTIDENTIFIER = 1;
  public int JJTMAINCLASS = 2;
  public int JJTCLASSDECL = 3;
  public int JJTINHERITANCE = 4;
  public int JJTVARDECLS = 5;
  public int JJTMETHODDECLS = 6;
  public int JJTVARDECL = 7;
  public int JJTMETHODDECL = 8;
  public int JJTARGS = 9;
  public int JJTVOID = 10;
  public int JJTARG = 11;
  public int JJTTYPE = 12;
  public int JJTBLOCK = 13;
  public int JJTIF = 14;
  public int JJTWHILE = 15;
  public int JJTPRINT = 16;
  public int JJTASSIGNMENT = 17;
  public int JJTORNODE = 18;
  public int JJTANDNODE = 19;
  public int JJTRELNODE = 20;
  public int JJTADDNODE = 21;
  public int JJTMULNODE = 22;
  public int JJTUNARYNODE = 23;
  public int JJTINTEGER = 24;
  public int JJTTRUE = 25;
  public int JJTFALSE = 26;
  public int JJTTHIS = 27;


  public String[] jjtNodeName = {
    "Program",
    "Identifier",
    "MainClass",
    "ClassDecl",
    "Inheritance",
    "VarDecls",
    "MethodDecls",
    "VarDecl",
    "MethodDecl",
    "Args",
    "void",
    "Arg",
    "Type",
    "Block",
    "If",
    "While",
    "Print",
    "Assignment",
    "OrNode",
    "AndNode",
    "RelNode",
    "AddNode",
    "MulNode",
    "UnaryNode",
    "Integer",
    "True",
    "False",
    "This",
  };
}
/* JavaCC - OriginalChecksum=4540438c5b2dcc5066d5dc782d19a28a (do not edit this line) */
